# This file was generated by GoReleaser. DO NOT EDIT.
class Dunner < Formula
  desc "A Docker based task runner tool"
  homepage "https://github.com/leopardslab/Dunner"
  url "https://github.com/leopardslab/dunner/releases/download/v2.1.1/dunner_2.1.1_darwin_x86_64.tar.gz"
  version "2.1.1"
  sha256 "fc1d0831264a30d1e3189db36ceeb0f8240c5f6489cec0e388bc8d87b98a4f86"

  def install
    bin.install "dunner"
  end

  test do
    system "#{bin}/dunner version"
  end
end
